name: Create Azure Storage (sameercv)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-storage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Resource Group exists
        run: |
          az group create \
            --name "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --location "${{ secrets.AZURE_LOCATION }}"

      - name: Validate names
        run: |
          STORAGE="${{ secrets.STORAGE_ACCOUNT_NAME }}"
          if [ ${#STORAGE} -lt 3 ] || [ ${#STORAGE} -gt 24 ]; then
            echo "❌ Storage account name length invalid (3–24 chars required)"
            exit 1
          fi

      - name: Create Storage Account
        run: |
          az storage account create \
            --name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --location "${{ secrets.AZURE_LOCATION }}" \
            --sku Standard_LRS \
            --kind StorageV2

      - name: Get Storage Account Key
        id: key
        run: |
          KEY=$(az storage account keys list \
            --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --query "[0].value" -o tsv)
          echo "key=$KEY" >> $GITHUB_OUTPUT

      - name: Enable Static Website Hosting
        run: |
          az storage blob service-properties update \
            --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --account-key "${{ steps.key.outputs.key }}" \
            --static-website \
            --index-document index.html \
            --404-document index.html

      - name: Upload only index.html
        run: |
          az storage blob upload \
            --file "index.html" \
            --container-name '$web' \
            --name "index.html" \
            --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --account-key "${{ steps.key.outputs.key }}"

      - name: Show Website URL
        run: |
          URL=$(az storage account show \
            --name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --query "primaryEndpoints.web" -o tsv)
          echo "🌐 Website URL: $URL"
